FROM 455926664280.dkr.ecr.eu-west-2.amazonaws.com/ts/stg/0/atf/php_app/base:v0.2.0

USER app
WORKDIR /var/www
COPY . .

USER root
RUN chown -R app:app /var/www/*

USER app

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm"]
