FROM docker:17-dind

USER root
RUN apk update && \
  apk add git nginx bash sudo ca-certificates s6 curl ssmtp php7 php7-phar php7-curl \
  php7-fpm php7-json php7-zlib php7-xml php7-dom php7-ctype php7-opcache php7-zip php7-iconv \
  php7-pdo php7-pdo_mysql php7-pdo_sqlite php7-pdo_pgsql php7-mbstring php7-session php7-tokenizer \
  php7-gd php7-mcrypt php7-openssl php7-sockets php7-posix php7-ldap php7-simplexml php7-fileinfo \
  python python-dev py-pip \
  nodejs nodejs-npm \
  docker && \
  rm -rf /var/cache/apk/* && \
  rm -f /etc/php7/php-fpm.d/www.conf && \
  touch /etc/php7/php-fpm.d/env.conf

RUN pip install awscli
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN rm -rf /var/www/* && mkdir /var/www/app

COPY files/conf.d/local.ini /etc/php7/conf.d/
COPY files/php-fpm.conf /etc/php7/

